### ISSUE TITLE
Skip already fitted Model if refit == FALSE, future.off==FALSE

### ISSUE THREAD

**Issue by nbungi** [GabelHub/FAMoS#1]
When FAMoS comes back to a model it already fitted and the following arguments were set, refit=FALSE, future.off=FALSE, it raises the following error.
`Error in UseMethod("value") :
  no applicable method for 'value' applied to an object of class "character"
Error in famos(init.par = inits, fit.fn = cost_function, nr.of.data = length(y.values),  :
  Future failed. The corresponding error message of job 10100 is shown above. If no output is shown, use 'future.off = TRUE' to debug.`

The error does not occur if future.off=TRUE. 

Error can be reproduced with your test.example.R, by sourcing it twice.

**Comment by GabelHub** [comment]
Hey nbungi ;)
Thanks for reporting. The error occurred because FAMoS previously assumed that all generated models were actually sent off by futures, if 'future.off = TRUE'. That issue should be fixed now. FAMoS now tracks which models were actually sent off by futures in each iteration.
